# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a206fdb883f6d1b6754d746d6f1e9761433856420d700e9d7997df2c2a097a4d00821a95b5cc7b6763d6a56c9f92b43297d9de9d7596433f40369445c564e04

test:
  secret_key_base: 3b8d41ace1f3bdabe1c6d514116b5602ce6c0b3db4ca7ff9c86dfb1f3bb80ad46cbd49da0eb97d7896f3fdb88d90a7268986a0584e67420dc215c251171207e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
